-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 加固注册触发器：username 元数据缺失时不再让注册整体失败
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_name TEXT;
BEGIN
  v_name := nullif(trim(coalesce(NEW.raw_user_meta_data ->> 'username', '')), '');
  IF v_name IS NULL THEN
    v_name := 'u_' || replace(NEW.id::text, '-', '');
  END IF;
  INSERT INTO public.profiles (id, username)
  VALUES (NEW.id, left(v_name, 40))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$fn$;

