-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS quiz_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bank_id UUID NOT NULL,
  mode TEXT NOT NULL DEFAULT 'seq',
  question_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  cursor INTEGER NOT NULL DEFAULT 0,
  total INTEGER NOT NULL DEFAULT 0,
  bank_name TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_progress_bank_mode ON quiz_progress(bank_id, mode);

ALTER TABLE quiz_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_quiz_progress ON quiz_progress FOR SELECT USING (true);
CREATE POLICY anon_insert_quiz_progress ON quiz_progress FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_quiz_progress ON quiz_progress FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY anon_delete_quiz_progress ON quiz_progress FOR DELETE USING (true);

