-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 模型二（千问）每日额度：新增「豁免名单」，名单内账号只记录次数、永不拦截
-- 智谱「模型一」本来就不计数、不停用，无需出现在此名单
CREATE TABLE IF NOT EXISTS public.quiz_ai_quota_exempt (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.quiz_ai_quota_exempt ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS select_own_quiz_ai_quota_exempt ON public.quiz_ai_quota_exempt;
CREATE POLICY select_own_quiz_ai_quota_exempt ON public.quiz_ai_quota_exempt
  FOR SELECT USING (user_id = auth.uid());

GRANT SELECT ON public.quiz_ai_quota_exempt TO authenticated;

-- 返回结构新增 unlimited，故必须先 DROP 再 CREATE
DROP FUNCTION IF EXISTS public.consume_qwen_quota(INTEGER);
CREATE FUNCTION public.consume_qwen_quota(p_limit INTEGER DEFAULT 2)
RETURNS TABLE(allowed BOOLEAN, used INTEGER, remaining INTEGER, quota_day DATE, unlimited BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_user UUID := auth.uid();
  v_limit INTEGER := GREATEST(COALESCE(p_limit, 2), 0);
  v_day DATE := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_exempt BOOLEAN := FALSE;
  v_used INTEGER;
BEGIN
  IF v_user IS NULL THEN
    RETURN QUERY SELECT FALSE, 0, v_limit, v_day, FALSE;
    RETURN;
  END IF;

  SELECT EXISTS (SELECT 1 FROM quiz_ai_quota_exempt e WHERE e.user_id = v_user) INTO v_exempt;

  INSERT INTO quiz_ai_quota (user_id, quota_day, qwen_calls)
  VALUES (v_user, v_day, 0)
  ON CONFLICT (user_id, quota_day) DO NOTHING;

  -- 豁免账号：照常累加次数（便于回看真实用量），但永远放行
  IF v_exempt THEN
    UPDATE quiz_ai_quota
       SET qwen_calls = qwen_calls + 1,
           updated_at = NOW()
     WHERE user_id = v_user
       AND quota_day = v_day
    RETURNING qwen_calls INTO v_used;
    RETURN QUERY SELECT TRUE, COALESCE(v_used, 0), v_limit, v_day, TRUE;
    RETURN;
  END IF;

  UPDATE quiz_ai_quota
     SET qwen_calls = qwen_calls + 1,
         updated_at = NOW()
   WHERE user_id = v_user
     AND quota_day = v_day
     AND qwen_calls < v_limit
  RETURNING qwen_calls INTO v_used;

  IF v_used IS NULL THEN
    SELECT q.qwen_calls INTO v_used
      FROM quiz_ai_quota q
     WHERE q.user_id = v_user AND q.quota_day = v_day;
    RETURN QUERY SELECT FALSE, COALESCE(v_used, v_limit), 0, v_day, FALSE;
    RETURN;
  END IF;

  RETURN QUERY SELECT TRUE, v_used, GREATEST(v_limit - v_used, 0), v_day, FALSE;
END;
$fn$;

DROP FUNCTION IF EXISTS public.get_qwen_quota(INTEGER);
CREATE FUNCTION public.get_qwen_quota(p_limit INTEGER DEFAULT 2)
RETURNS TABLE(used INTEGER, remaining INTEGER, quota_day DATE, unlimited BOOLEAN)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_user UUID := auth.uid();
  v_limit INTEGER := GREATEST(COALESCE(p_limit, 2), 0);
  v_day DATE := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_used INTEGER := 0;
  v_exempt BOOLEAN := FALSE;
BEGIN
  IF v_user IS NULL THEN
    RETURN QUERY SELECT 0, v_limit, v_day, FALSE;
    RETURN;
  END IF;

  SELECT EXISTS (SELECT 1 FROM quiz_ai_quota_exempt e WHERE e.user_id = v_user) INTO v_exempt;

  SELECT COALESCE(MAX(q.qwen_calls), 0) INTO v_used
    FROM quiz_ai_quota q
   WHERE q.user_id = v_user AND q.quota_day = v_day;

  RETURN QUERY SELECT v_used, GREATEST(v_limit - v_used, 0), v_day, v_exempt;
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.consume_qwen_quota(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_qwen_quota(INTEGER) TO authenticated;

