-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 内置「模型二 · 通义千问」每人每天调用额度
-- 口径：一次真正打到千问上游的请求 = 一次额度（含智谱失败后的自动降级那一次）
-- 自然日按 Asia/Shanghai 计算，次日 00:00 自动归零（新的一天是新的一行）
-- 智谱「模型一」不计数、不限次，用户可自行反复重试

CREATE TABLE IF NOT EXISTS public.quiz_ai_quota (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  quota_day DATE NOT NULL DEFAULT ((now() AT TIME ZONE 'Asia/Shanghai')::date),
  qwen_calls INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT quiz_ai_quota_user_day_unique UNIQUE (user_id, quota_day)
);

CREATE INDEX IF NOT EXISTS quiz_ai_quota_user_day_idx
  ON public.quiz_ai_quota (user_id, quota_day);

ALTER TABLE public.quiz_ai_quota ENABLE ROW LEVEL SECURITY;

-- 客户端只读自己的额度，写入一律走 SECURITY DEFINER 函数，避免自行把计数改小
DROP POLICY IF EXISTS select_own_quiz_ai_quota ON public.quiz_ai_quota;
CREATE POLICY select_own_quiz_ai_quota ON public.quiz_ai_quota
  FOR SELECT USING (user_id = auth.uid());

-- 原子「检查 + 扣一次」：额度够就 +1 并返回 allowed=true，不够则原样返回 allowed=false
CREATE OR REPLACE FUNCTION public.consume_qwen_quota(p_limit INTEGER DEFAULT 2)
RETURNS TABLE(allowed BOOLEAN, used INTEGER, remaining INTEGER, quota_day DATE)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_user UUID := auth.uid();
  v_limit INTEGER := GREATEST(COALESCE(p_limit, 2), 0);
  v_day DATE := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_used INTEGER;
BEGIN
  IF v_user IS NULL THEN
    RETURN QUERY SELECT FALSE, 0, v_limit, v_day;
    RETURN;
  END IF;

  INSERT INTO quiz_ai_quota (user_id, quota_day, qwen_calls)
  VALUES (v_user, v_day, 0)
  ON CONFLICT (user_id, quota_day) DO NOTHING;

  UPDATE quiz_ai_quota
     SET qwen_calls = qwen_calls + 1,
         updated_at = NOW()
   WHERE user_id = v_user
     AND quota_day = v_day
     AND qwen_calls < v_limit
  RETURNING qwen_calls INTO v_used;

  IF v_used IS NULL THEN
    SELECT q.qwen_calls INTO v_used
      FROM quiz_ai_quota q
     WHERE q.user_id = v_user AND q.quota_day = v_day;
    RETURN QUERY SELECT FALSE, COALESCE(v_used, v_limit), 0, v_day;
    RETURN;
  END IF;

  RETURN QUERY SELECT TRUE, v_used, GREATEST(v_limit - v_used, 0), v_day;
END;
$fn$;

-- 只读当前额度，供设置页展示「今日剩余 X/2」
CREATE OR REPLACE FUNCTION public.get_qwen_quota(p_limit INTEGER DEFAULT 2)
RETURNS TABLE(used INTEGER, remaining INTEGER, quota_day DATE)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_user UUID := auth.uid();
  v_limit INTEGER := GREATEST(COALESCE(p_limit, 2), 0);
  v_day DATE := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_used INTEGER := 0;
BEGIN
  IF v_user IS NULL THEN
    RETURN QUERY SELECT 0, v_limit, v_day;
    RETURN;
  END IF;

  SELECT COALESCE(MAX(q.qwen_calls), 0) INTO v_used
    FROM quiz_ai_quota q
   WHERE q.user_id = v_user AND q.quota_day = v_day;

  RETURN QUERY SELECT v_used, GREATEST(v_limit - v_used, 0), v_day;
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.consume_qwen_quota(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_qwen_quota(INTEGER) TO authenticated;

