-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.quiz_vision_jobs (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'running',
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS quiz_vision_jobs_user_created
  ON public.quiz_vision_jobs (user_id, created_at DESC);

ALTER TABLE public.quiz_vision_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_all_quiz_vision_jobs ON public.quiz_vision_jobs;
CREATE POLICY user_all_quiz_vision_jobs ON public.quiz_vision_jobs
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

