-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE quiz_banks ADD COLUMN IF NOT EXISTS device_id TEXT NOT NULL DEFAULT '';
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS device_id TEXT NOT NULL DEFAULT '';
ALTER TABLE quiz_attempts ADD COLUMN IF NOT EXISTS device_id TEXT NOT NULL DEFAULT '';
ALTER TABLE quiz_wrong_book ADD COLUMN IF NOT EXISTS device_id TEXT NOT NULL DEFAULT '';
ALTER TABLE quiz_progress ADD COLUMN IF NOT EXISTS device_id TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_banks_device_created ON quiz_banks (device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_questions_device_bank ON quiz_questions (device_id, bank_id);
CREATE INDEX IF NOT EXISTS idx_attempts_device_created ON quiz_attempts (device_id, created_at);
CREATE INDEX IF NOT EXISTS idx_wrong_device_bank ON quiz_wrong_book (device_id, bank_id);
CREATE INDEX IF NOT EXISTS idx_progress_device_bank ON quiz_progress (device_id, bank_id, mode);
