-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 智能刷题系统核心数据表
CREATE TABLE IF NOT EXISTS quiz_banks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  source_file TEXT,
  is_ai_bank BOOLEAN NOT NULL DEFAULT FALSE,
  question_count INTEGER NOT NULL DEFAULT 0,
  reviewed_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bank_id UUID NOT NULL REFERENCES quiz_banks(id) ON DELETE CASCADE,
  type TEXT NOT NULL DEFAULT 'choice',
  stem TEXT NOT NULL,
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  answer TEXT NOT NULL DEFAULT '',
  answer_bool BOOLEAN,
  explanation TEXT,
  confidence NUMERIC(3,2) NOT NULL DEFAULT 0.5,
  reviewed BOOLEAN NOT NULL DEFAULT FALSE,
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_questions_bank ON quiz_questions(bank_id, order_index);

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id UUID,
  bank_id UUID,
  correct BOOLEAN NOT NULL DEFAULT FALSE,
  mode TEXT NOT NULL DEFAULT 'seq',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_attempts_created ON quiz_attempts(created_at);

CREATE TABLE IF NOT EXISTS quiz_wrong_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id UUID NOT NULL,
  bank_id UUID NOT NULL,
  wrong_count INTEGER NOT NULL DEFAULT 1,
  streak_correct INTEGER NOT NULL DEFAULT 0,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wrong_unique ON quiz_wrong_book(question_id);

CREATE TABLE IF NOT EXISTS quiz_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  default_mode TEXT NOT NULL DEFAULT 'seq',
  allow_type_convert BOOLEAN NOT NULL DEFAULT TRUE,
  haptic_on_wrong BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE quiz_banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_wrong_book ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_quiz_banks ON quiz_banks FOR SELECT USING (true);
CREATE POLICY anon_insert_quiz_banks ON quiz_banks FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_quiz_banks ON quiz_banks FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY anon_delete_quiz_banks ON quiz_banks FOR DELETE USING (true);

CREATE POLICY anon_select_quiz_questions ON quiz_questions FOR SELECT USING (true);
CREATE POLICY anon_insert_quiz_questions ON quiz_questions FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_quiz_questions ON quiz_questions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY anon_delete_quiz_questions ON quiz_questions FOR DELETE USING (true);

CREATE POLICY anon_select_quiz_attempts ON quiz_attempts FOR SELECT USING (true);
CREATE POLICY anon_insert_quiz_attempts ON quiz_attempts FOR INSERT WITH CHECK (true);
CREATE POLICY anon_delete_quiz_attempts ON quiz_attempts FOR DELETE USING (true);

CREATE POLICY anon_select_quiz_wrong_book ON quiz_wrong_book FOR SELECT USING (true);
CREATE POLICY anon_insert_quiz_wrong_book ON quiz_wrong_book FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_quiz_wrong_book ON quiz_wrong_book FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY anon_delete_quiz_wrong_book ON quiz_wrong_book FOR DELETE USING (true);

CREATE POLICY anon_select_quiz_settings ON quiz_settings FOR SELECT USING (true);
CREATE POLICY anon_insert_quiz_settings ON quiz_settings FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_quiz_settings ON quiz_settings FOR UPDATE USING (true) WITH CHECK (true);

