-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 修复：RETURNS TABLE 的 OUT 参数名 quota_day 与表列同名，
-- plpgsql 在 UPDATE ... WHERE quota_day = v_day 处报 42702「column reference is ambiguous」，
-- 导致 consume_qwen_quota 从未真正扣减成功（云函数 catch 后默认放行，所以表现为「限额不生效」）。
-- 做法：输出列改名 quota_date，函数体内所有列引用一律带表别名限定。

DROP FUNCTION IF EXISTS public.consume_qwen_quota(INTEGER);
CREATE FUNCTION public.consume_qwen_quota(p_limit INTEGER DEFAULT 2)
RETURNS TABLE(allowed BOOLEAN, used INTEGER, remaining INTEGER, quota_date DATE, unlimited BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_user UUID := auth.uid();
  v_limit INTEGER := GREATEST(COALESCE(p_limit, 2), 0);
  v_day DATE := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_exempt BOOLEAN := FALSE;
  v_used INTEGER;
BEGIN
  IF v_user IS NULL THEN
    RETURN QUERY SELECT FALSE, 0, v_limit, v_day, FALSE;
    RETURN;
  END IF;

  SELECT EXISTS (SELECT 1 FROM quiz_ai_quota_exempt e WHERE e.user_id = v_user) INTO v_exempt;

  INSERT INTO quiz_ai_quota (user_id, quota_day, qwen_calls)
  VALUES (v_user, v_day, 0)
  ON CONFLICT (user_id, quota_day) DO NOTHING;

  -- 豁免账号：照常累加次数（便于回看真实用量），但永远放行
  IF v_exempt THEN
    UPDATE quiz_ai_quota AS q
       SET qwen_calls = q.qwen_calls + 1,
           updated_at = NOW()
     WHERE q.user_id = v_user
       AND q.quota_day = v_day
    RETURNING q.qwen_calls INTO v_used;
    RETURN QUERY SELECT TRUE, COALESCE(v_used, 0), v_limit, v_day, TRUE;
    RETURN;
  END IF;

  UPDATE quiz_ai_quota AS q
     SET qwen_calls = q.qwen_calls + 1,
         updated_at = NOW()
   WHERE q.user_id = v_user
     AND q.quota_day = v_day
     AND q.qwen_calls < v_limit
  RETURNING q.qwen_calls INTO v_used;

  IF v_used IS NULL THEN
    SELECT q.qwen_calls INTO v_used
      FROM quiz_ai_quota q
     WHERE q.user_id = v_user
       AND q.quota_day = v_day;
    RETURN QUERY SELECT FALSE, COALESCE(v_used, v_limit), 0, v_day, FALSE;
    RETURN;
  END IF;

  RETURN QUERY SELECT TRUE, v_used, GREATEST(v_limit - v_used, 0), v_day, FALSE;
END;
$fn$;

DROP FUNCTION IF EXISTS public.get_qwen_quota(INTEGER);
CREATE FUNCTION public.get_qwen_quota(p_limit INTEGER DEFAULT 2)
RETURNS TABLE(used INTEGER, remaining INTEGER, quota_date DATE, unlimited BOOLEAN)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_user UUID := auth.uid();
  v_limit INTEGER := GREATEST(COALESCE(p_limit, 2), 0);
  v_day DATE := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_used INTEGER := 0;
  v_exempt BOOLEAN := FALSE;
BEGIN
  IF v_user IS NULL THEN
    RETURN QUERY SELECT 0, v_limit, v_day, FALSE;
    RETURN;
  END IF;

  SELECT EXISTS (SELECT 1 FROM quiz_ai_quota_exempt e WHERE e.user_id = v_user) INTO v_exempt;

  SELECT COALESCE(MAX(q.qwen_calls), 0) INTO v_used
    FROM quiz_ai_quota q
   WHERE q.user_id = v_user
     AND q.quota_day = v_day;

  RETURN QUERY SELECT v_used, GREATEST(v_limit - v_used, 0), v_day, v_exempt;
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.consume_qwen_quota(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_qwen_quota(INTEGER) TO authenticated;

