-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE quiz_settings ADD COLUMN IF NOT EXISTS exam_seconds_per_question INTEGER NOT NULL DEFAULT 60;
