-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE quiz_settings ADD COLUMN IF NOT EXISTS device_id TEXT NOT NULL DEFAULT '';
DELETE FROM quiz_settings WHERE device_id = '';
ALTER TABLE quiz_settings DROP CONSTRAINT IF EXISTS quiz_settings_id_check;
ALTER TABLE quiz_settings DROP CONSTRAINT IF EXISTS quiz_settings_pkey;
ALTER TABLE quiz_settings ALTER COLUMN device_id SET DEFAULT '';
ALTER TABLE quiz_settings DROP COLUMN IF EXISTS id;
ALTER TABLE quiz_settings ADD CONSTRAINT quiz_settings_pkey PRIMARY KEY (device_id);
