-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 批次3：题目收藏 + 间隔重复复习 + 每日目标

CREATE TABLE IF NOT EXISTS quiz_favorites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  question_id UUID NOT NULL,
  bank_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  question_id UUID NOT NULL,
  bank_id UUID NOT NULL,
  box SMALLINT NOT NULL DEFAULT 1,
  due_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_review_at TIMESTAMPTZ,
  review_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_favorites_unique ON quiz_favorites(user_id, question_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user_created ON quiz_favorites(user_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_reviews_unique ON quiz_reviews(user_id, question_id);
CREATE INDEX IF NOT EXISTS idx_reviews_due ON quiz_reviews(user_id, due_at);

ALTER TABLE quiz_settings ADD COLUMN IF NOT EXISTS daily_goal INTEGER NOT NULL DEFAULT 20;

ALTER TABLE quiz_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS users_select_own_favorites ON quiz_favorites;
DROP POLICY IF EXISTS users_insert_own_favorites ON quiz_favorites;
DROP POLICY IF EXISTS users_delete_own_favorites ON quiz_favorites;
CREATE POLICY users_select_own_favorites ON quiz_favorites FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_own_favorites ON quiz_favorites FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_delete_own_favorites ON quiz_favorites FOR DELETE USING (user_id = auth.uid());

DROP POLICY IF EXISTS users_select_own_reviews ON quiz_reviews;
DROP POLICY IF EXISTS users_insert_own_reviews ON quiz_reviews;
DROP POLICY IF EXISTS users_update_own_reviews ON quiz_reviews;
DROP POLICY IF EXISTS users_delete_own_reviews ON quiz_reviews;
CREATE POLICY users_select_own_reviews ON quiz_reviews FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_own_reviews ON quiz_reviews FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_own_reviews ON quiz_reviews FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY users_delete_own_reviews ON quiz_reviews FOR DELETE USING (user_id = auth.uid());

