-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS difficulty SMALLINT; CREATE INDEX IF NOT EXISTS idx_questions_difficulty ON quiz_questions(bank_id, difficulty);
