/**
 * This file is auto-generated by Meoo Cloud. Do not edit manually.
 */

import { Platform } from 'react-native';
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

if (Platform.OS !== 'web') {
  require('react-native-url-polyfill/auto');
}

const PROJECT_URL_ID = "e582lpwt1ri0";

export const supabaseUrl = "https://tp5m415y2fjx8v5m.database.meoo.xyz";
export const supabaseAnonKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg0NjAzMDE4LCJleHAiOjEzMjk1MjQzMDE4fQ.Yqc3SBQSvtMn6SD7Ob-E-dKDPPKK4M5P963glCi9_zI";

const PlatformStorageAdapter = {
  getItem: (key: string): Promise<string | null> => {
    if (Platform.OS === 'web') {
      try {
        return Promise.resolve(
          typeof localStorage !== 'undefined' ? localStorage.getItem(key) : null
        );
      } catch {
        return Promise.resolve(null);
      }
    }
    const SecureStore = require('expo-secure-store');
    return SecureStore.getItemAsync(key);
  },
  setItem: (key: string, value: string): Promise<void> => {
    if (Platform.OS === 'web') {
      try {
        if (typeof localStorage !== 'undefined') localStorage.setItem(key, value);
      } catch {
        // Ignore unavailable browser storage.
      }
      return Promise.resolve();
    }
    const SecureStore = require('expo-secure-store');
    return SecureStore.setItemAsync(key, value);
  },
  removeItem: (key: string): Promise<void> => {
    if (Platform.OS === 'web') {
      try {
        if (typeof localStorage !== 'undefined') localStorage.removeItem(key);
      } catch {
        // Ignore unavailable browser storage.
      }
      return Promise.resolve();
    }
    const SecureStore = require('expo-secure-store');
    return SecureStore.deleteItemAsync(key);
  },
};

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: PlatformStorageAdapter,
  },
  global: {
    // React Native 请求同样携带项目上下文；实例 URL 本身只能定位共享后端。
    headers: PROJECT_URL_ID ? { 'OneDay-App-Id': PROJECT_URL_ID } : {},
  },
});
