// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          id: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          id: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          username?: string
        }
        Relationships: []
      }
      quiz_ai_quota: {
        Row: {
          created_at: string
          id: string
          quota_day: string
          qwen_calls: number
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          quota_day?: string
          qwen_calls?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          quota_day?: string
          qwen_calls?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      quiz_ai_quota_exempt: {
        Row: {
          created_at: string
          note: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          note?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          note?: string | null
          user_id?: string
        }
        Relationships: []
      }
      quiz_attempts: {
        Row: {
          bank_id: string | null
          correct: boolean
          created_at: string
          device_id: string
          id: string
          mode: string
          question_id: string | null
          user_id: string | null
        }
        Insert: {
          bank_id?: string | null
          correct?: boolean
          created_at?: string
          device_id?: string
          id?: string
          mode?: string
          question_id?: string | null
          user_id?: string | null
        }
        Update: {
          bank_id?: string | null
          correct?: boolean
          created_at?: string
          device_id?: string
          id?: string
          mode?: string
          question_id?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      quiz_banks: {
        Row: {
          created_at: string
          device_id: string
          id: string
          is_ai_bank: boolean
          name: string
          question_count: number
          reviewed_count: number
          source_file: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          device_id?: string
          id?: string
          is_ai_bank?: boolean
          name: string
          question_count?: number
          reviewed_count?: number
          source_file?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          device_id?: string
          id?: string
          is_ai_bank?: boolean
          name?: string
          question_count?: number
          reviewed_count?: number
          source_file?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: []
      }
      quiz_favorites: {
        Row: {
          bank_id: string
          created_at: string
          id: string
          question_id: string
          user_id: string
        }
        Insert: {
          bank_id: string
          created_at?: string
          id?: string
          question_id: string
          user_id: string
        }
        Update: {
          bank_id?: string
          created_at?: string
          id?: string
          question_id?: string
          user_id?: string
        }
        Relationships: []
      }
      quiz_progress: {
        Row: {
          answers: Json
          bank_id: string
          bank_name: string | null
          cursor: number
          device_id: string
          id: string
          mode: string
          question_ids: Json
          total: number
          updated_at: string
          user_id: string | null
        }
        Insert: {
          answers?: Json
          bank_id: string
          bank_name?: string | null
          cursor?: number
          device_id?: string
          id?: string
          mode?: string
          question_ids?: Json
          total?: number
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          answers?: Json
          bank_id?: string
          bank_name?: string | null
          cursor?: number
          device_id?: string
          id?: string
          mode?: string
          question_ids?: Json
          total?: number
          updated_at?: string
          user_id?: string | null
        }
        Relationships: []
      }
      quiz_questions: {
        Row: {
          answer: string
          answer_bool: boolean | null
          bank_id: string
          confidence: number
          created_at: string
          device_id: string
          difficulty: number | null
          explanation: string | null
          id: string
          options: Json
          order_index: number
          reviewed: boolean
          stem: string
          subject: string | null
          type: string
          user_id: string | null
        }
        Insert: {
          answer?: string
          answer_bool?: boolean | null
          bank_id: string
          confidence?: number
          created_at?: string
          device_id?: string
          difficulty?: number | null
          explanation?: string | null
          id?: string
          options?: Json
          order_index?: number
          reviewed?: boolean
          stem: string
          subject?: string | null
          type?: string
          user_id?: string | null
        }
        Update: {
          answer?: string
          answer_bool?: boolean | null
          bank_id?: string
          confidence?: number
          created_at?: string
          device_id?: string
          difficulty?: number | null
          explanation?: string | null
          id?: string
          options?: Json
          order_index?: number
          reviewed?: boolean
          stem?: string
          subject?: string | null
          type?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quiz_questions_bank_id_fkey"
            columns: ["bank_id"]
            referencedRelation: "quiz_banks"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_reviews: {
        Row: {
          bank_id: string
          box: number
          created_at: string
          due_at: string
          id: string
          last_review_at: string | null
          question_id: string
          review_count: number
          user_id: string
        }
        Insert: {
          bank_id: string
          box?: number
          created_at?: string
          due_at?: string
          id?: string
          last_review_at?: string | null
          question_id: string
          review_count?: number
          user_id: string
        }
        Update: {
          bank_id?: string
          box?: number
          created_at?: string
          due_at?: string
          id?: string
          last_review_at?: string | null
          question_id?: string
          review_count?: number
          user_id?: string
        }
        Relationships: []
      }
      quiz_settings: {
        Row: {
          allow_type_convert: boolean
          daily_goal: number
          default_mode: string
          device_id: string
          exam_seconds_per_question: number
          haptic_on_wrong: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          allow_type_convert?: boolean
          daily_goal?: number
          default_mode?: string
          device_id?: string
          exam_seconds_per_question?: number
          haptic_on_wrong?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          allow_type_convert?: boolean
          daily_goal?: number
          default_mode?: string
          device_id?: string
          exam_seconds_per_question?: number
          haptic_on_wrong?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      quiz_vision_jobs: {
        Row: {
          created_at: string
          error: string | null
          id: string
          questions: Json
          status: string
          user_id: string
        }
        Insert: {
          created_at?: string
          error?: string | null
          id: string
          questions?: Json
          status?: string
          user_id: string
        }
        Update: {
          created_at?: string
          error?: string | null
          id?: string
          questions?: Json
          status?: string
          user_id?: string
        }
        Relationships: []
      }
      quiz_wrong_book: {
        Row: {
          bank_id: string
          device_id: string
          id: string
          question_id: string
          resolved: boolean
          streak_correct: number
          updated_at: string
          user_id: string | null
          wrong_count: number
        }
        Insert: {
          bank_id: string
          device_id?: string
          id?: string
          question_id: string
          resolved?: boolean
          streak_correct?: number
          updated_at?: string
          user_id?: string | null
          wrong_count?: number
        }
        Update: {
          bank_id?: string
          device_id?: string
          id?: string
          question_id?: string
          resolved?: boolean
          streak_correct?: number
          updated_at?: string
          user_id?: string | null
          wrong_count?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      consume_qwen_quota: {
        Args: { p_limit?: number }
        Returns: {
          allowed: boolean
          used: number
          remaining: number
          quota_date: string
          unlimited: boolean
        }[]
      }
      get_qwen_quota: {
        Args: { p_limit?: number }
        Returns: {
          used: number
          remaining: number
          quota_date: string
          unlimited: boolean
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
